### ISSUE TITLE
Versionning is working weirdly when the moderator edits questions

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-questions#20]
**Describe the bug**
 - When question "description" field is edited by moderator html markup <p> appears on the question list. : https://participons.debatpublic.fr/processes/nfl/f/37/
- When changing the state a new version is created for each field and adding <p></p> on the description field : https://participons.debatpublic.fr/processes/nfl/f/37/questions/5/versions/2
- Empty versions are created : https://participons.debatpublic.fr/processes/nfl/f/37/questions/5/versions/3

**Comment by lu-hamani** [comment]
@moustachu or/and @armandfardeau, I need you insights on this one and the inner workings of paper trail. Obviously this is a "confusing" bug rather than a "blocking bug".
How can we prevent this bug without breaking the versioning system ?

**Comment by lu-hamani** [comment]
So from what I observed, the "weird" versions are the one created by service and committee assignment.
When a question is assigned to the committee/service, a new version is created, yet it displays nothing on the version's show page. 
So we face the following dilemma : 
The versioning system has been used as transparency safeguard regarding upstream moderation. The fact that a version of question is created on a question's assignment is positive. Yet since it displays no information, it has no added value to the user and displaying any information can put unwanted pressure on the client. We also have to take into account the purely technical aspect of the problem, since tweaking papertrail might breal all hell loose.
