### ISSUE TITLE
Some users get a server error at publish stage

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-questions#33]
**Describe the bug**
![cednjldpjmfjmefp](https://user-images.githubusercontent.com/11473995/57777065-3d71b900-7721-11e9-8299-8446aa8e07f2.jpg)

Forwarding you via email the details.
I was not able to replicate the bug. 

**Stacktrace**
I found a error in [Sentry](https://sentry.io/organizations/open-source-politics/issues/1022048052/?project=1436134&query=is%3Aunresolved) that seems related.

**Extra data (please complete the following information):**
 - Decidim Version: 0.16
 - Decidim installation: CNDP

**Comment by moustachu** [comment]
@virgile-dev : This comes from a translation key overwrited with the term customizer on the platform.
The corrupt key is `decidim.admin.upstream_moderation_mailer.notify_moderator.report_html` in the [_NFL Avis_ pack](https://participons.debatpublic.fr/admin/term_customizer/sets/1/translations)

In the modified value : a `%{title}` was inserted but it cannot work since this variable is not manage in the code.

#### ➡️ You need to remove the `%{title}` in the modified value to fix the issue.

**Comment by virgile-dev** [comment]
Ok thanks @moustachu ! 
I think it's Jean-Yves who tried to insert variables in the translation modules. Will let him know that this causes the application crashes.

**Comment by virgile-dev** [comment]
%{title} Translation removed from pack.
