### ISSUE TITLE
Avis has "En attente de réponse" state

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-questions#53]
**Describe the bug**
An avis has the state "En attente de réponse" when I see no actions made by the moderator.
This was seen by JY, here is the [ticket](https://support.opensourcepolitics.eu/scp/tickets.php?id=203)

@moustachu can you check this error ?

**To Reproduce**
This is the avis : https://participons.debatpublic.fr/processes/nfl/f/38/questions/466

**Quick solution**
Just publish the avis. That's what I told them to do.

**Comment by moustachu** [comment]
@virgile-dev Please describe "when I see no actions made by the moderator"

I don't see any anomaly : 
- the state was change to `evaluating` by a "process admin" (https://participons.debatpublic.fr/processes/nfl/f/38/questions/466/versions/3)
- BUT **without** any recipient selected (`committee` or `service`) 

Do you mean that since "Answer are not enabled", we should display "Evaluating" instead of "Awaiting answer" ?
